#!/bin/bash

export CURRENT_WEEK=1
export CURRENT_SEASON=season-23

PREGAME="\"pregame\""
MATCH_DIR="$CURRENT_SEASON/matches"
TEMP_DIR="$CURRENT_SEASON/tmp"

# BACKUP any matches that have been played
mkdir "$TEMP_DIR"
for input_file in "$MATCH_DIR"/*.json; do
    # find out what state the match is in
    COMMAND_OUTPUT=$(jq '.state' "$input_file")

    if [ "$COMMAND_OUTPUT" == "$PREGAME" ]; then
        echo "rm $input_file"
    else
        echo "mv $input_file $TEMP_DIR"
    fi
done

# CREATE all the matches
export DATA_FOLDER=/home/mnpdocker/apps/mnpdocker/mnp-data-archive
pushd "$DATA_FOLDER"
git pull
popd
node ../importers/export-season.js "$CURRENT_SEASON" > "$CURRENT_SEASON/rosters.csv"
export DATA_FOLDER=/home/mnpdocker/apps/mnpdocker/main/data
node ../importers/import-season.js "$CURRENT_SEASON"
node ../util/spawn-matches.js "$CURRENT_WEEK"

# RESTORE any matches that have been played
for input_file in "$TEMP_DIR"/*.json; do
    echo "mv $input_file $MATCH_DIR"
done
rmdir "$TEMP_DIR"